# config/services.yaml

# Déclaration des paramètres
parameters:
    articles_per_page: 5

# Déclaration des services
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Service\SpamFinder:
        arguments:
            $spamWords: ['aaaaa', 'sdfsdf']
        autowire: true
        autoconfigure: false
        public: false
    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]

    # Enregistrement automatique des services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

